[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "Dyner - More dyn than ever"

[output.html]
git-repository-url = "https://github.com/nikomatsakis/dyner"
edit-url-template = "https://github.com/nikomatsakis/dyner/edit/master/{path}"